**Theme:**

*“All deep learning is just this loop, repeated correctly.”*

In [1]:
import torch 
import torch.nn as nn 


torch.__version__

'2.8.0+cu129'

# The Training Loop (Core of All DL)

**The one loop that rules everything** <br> 
```python
for each batch:
    zero gradients
    forward pass
    compute loss
    backward pass
    update weights
```

In [2]:
dtype = torch.float 
device = torch.cuda

## Minimal training (No dataset yet)

In [72]:
torch.manual_seed(22)

x = torch.tensor([1,2,3,4], dtype=dtype) 
y_true = torch.tensor([3,5,7,9], dtype=dtype) 

class LinearModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.w = nn.Parameter(torch.randn(1)) 
        self.b = nn.Parameter(torch.randn(1)) 

    def forward(self,x): 
        y = self.w * x + self.b 
        return y 
    

model = LinearModel() 
loss_fn = nn.MSELoss() 
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

print('w',model.w,', b',model.b)

w Parameter containing:
tensor([1.0302], requires_grad=True) , b Parameter containing:
tensor([-0.5073], requires_grad=True)


## One trainign step (Manual)

In [73]:
y_pred = model(x) 
loss = loss_fn(y_true,y_pred) 

optimizer.zero_grad() 
loss.backward() 
optimizer.step()

print("Loss:",loss.item()) 
print("w:",model.w.item(), ", b:",model.b.item())

Loss: 16.633920669555664
w: 3.238523483276367 , b: 0.2790701985359192


- What happened to `w` and `b`?

- Why was `zero_grad()` before `backward()`?

## Turning it into a loop

In [74]:
epochs = 20 

for epoch in range(epochs): 
    # Forward pass
    y_pred = model(x) 
    # Compute loss
    loss = loss_fn(y_true,y_pred) 

    # Zero gradients
    optimizer.zero_grad()
    # Backward pass
    loss.backward() 
    # Weights update
    optimizer.step()

    print(f"Epoch: {epoch+1}, Loss: {loss.item():.4f}, w: {model.w.item():.4f}, b: {model.b.item():.4f}")

Epoch: 1, Loss: 7.5598, w: 1.7412, b: -0.1960
Epoch: 2, Loss: 3.4804, w: 2.7274, b: 0.1726
Epoch: 3, Loss: 1.6437, w: 2.0500, b: -0.0256
Epoch: 4, Loss: 0.8142, w: 2.4878, b: 0.1545
Epoch: 5, Loss: 0.4373, w: 2.1788, b: 0.0797
Epoch: 6, Loss: 0.2639, w: 2.3707, b: 0.1743
Epoch: 7, Loss: 0.1820, w: 2.2275, b: 0.1541
Epoch: 8, Loss: 0.1415, w: 2.3092, b: 0.2095
Epoch: 9, Loss: 0.1198, w: 2.2406, b: 0.2130
Epoch: 10, Loss: 0.1068, w: 2.2732, b: 0.2501
Epoch: 11, Loss: 0.0978, w: 2.2384, b: 0.2635
Epoch: 12, Loss: 0.0908, w: 2.2491, b: 0.2916
Epoch: 13, Loss: 0.0849, w: 2.2297, b: 0.3088
Epoch: 14, Loss: 0.0796, w: 2.2308, b: 0.3322
Epoch: 15, Loss: 0.0748, w: 2.2185, b: 0.3504
Epoch: 16, Loss: 0.0704, w: 2.2156, b: 0.3710
Epoch: 17, Loss: 0.0662, w: 2.2067, b: 0.3890
Epoch: 18, Loss: 0.0623, w: 2.2021, b: 0.4079
Epoch: 19, Loss: 0.0586, w: 2.1950, b: 0.4252
Epoch: 20, Loss: 0.0551, w: 2.1899, b: 0.4427


- What happens to loss?

- Where is “learning” happening?

## Break it on purpose 
- Removing `optimizer.zero_grad()`

In [76]:
epochs = 20 

for epoch in range(epochs): 
    # Forward pass
    y_pred = model(x) 
    # Compute loss
    loss = loss_fn(y_true,y_pred) 
    

    # # Zero gradients
    # optimizer.zero_grad()

    # Backward pass
    loss.backward() 
    # Weights update
    optimizer.step()

    print(f"Epoch: {epoch+1}, Loss: {loss.item():.4f}, w: {model.w.item():.4f}, b: {model.b.item():.4f}")

Epoch: 1, Loss: 0.0093, w: 1.8899, b: 1.3231
Epoch: 2, Loss: 0.0174, w: 1.8631, b: 1.4005
Epoch: 3, Loss: 0.0268, w: 1.8414, b: 1.4662
Epoch: 4, Loss: 0.0363, w: 1.8245, b: 1.5180
Epoch: 5, Loss: 0.0448, w: 1.8118, b: 1.5539
Epoch: 6, Loss: 0.0512, w: 1.8045, b: 1.5731
Epoch: 7, Loss: 0.0549, w: 1.8038, b: 1.5755
Epoch: 8, Loss: 0.0553, w: 1.8097, b: 1.5608
Epoch: 9, Loss: 0.0525, w: 1.8206, b: 1.5292
Epoch: 10, Loss: 0.0467, w: 1.8360, b: 1.4814
Epoch: 11, Loss: 0.0387, w: 1.8568, b: 1.4193
Epoch: 12, Loss: 0.0294, w: 1.8827, b: 1.3450
Epoch: 13, Loss: 0.0199, w: 1.9121, b: 1.2603
Epoch: 14, Loss: 0.0113, w: 1.9432, b: 1.1675
Epoch: 15, Loss: 0.0047, w: 1.9757, b: 1.0697
Epoch: 16, Loss: 0.0008, w: 2.0098, b: 0.9700
Epoch: 17, Loss: 0.0002, w: 2.0442, b: 0.8714
Epoch: 18, Loss: 0.0028, w: 2.0766, b: 0.7764
Epoch: 19, Loss: 0.0084, w: 2.1059, b: 0.6879
Epoch: 20, Loss: 0.0163, w: 2.1324, b: 0.6088


- What happens to loss?

- Why does it explode or behave strangely?

## Understand the gradient flow

In [85]:
torch.manual_seed(33)
epochs = 10 
model = LinearModel() 
loss_fn = nn.MSELoss() 
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

print('w',model.w,', b',model.b,'\n\n')




for epoch in range(epochs): 
    # Forward pass
    y_pred = model(x) 
    # Compute loss
    loss = loss_fn(y_true,y_pred) 

    # Zero gradients
    optimizer.zero_grad()
    # Backward pass
    loss.backward() 
    # Weights update
    optimizer.step()

    print(f"lr * grad w: {0.1*model.w.grad.item():.4f}, lr * grad b: {0.1*model.b.grad.item():.4f} \n")
    print(f"Epoch: {epoch+1}, Loss: {loss.item():.4f}, w: {model.w.item():.4f}, b: {model.b.item():.4f}")


w Parameter containing:
tensor([1.1982], requires_grad=True) , b Parameter containing:
tensor([-0.3998], requires_grad=True) 


lr * grad w: -1.9026, lr * grad b: -0.6809 

Epoch: 1, Loss: 12.3932, w: 3.1008, b: 0.2810
lr * grad w: 1.2917, lr * grad b: 0.4066 

Epoch: 2, Loss: 5.6482, w: 1.8091, b: -0.1256
lr * grad w: -0.8492, lr * grad b: -0.3206 

Epoch: 3, Loss: 2.6149, w: 2.6583, b: 0.1950
lr * grad w: 0.5849, lr * grad b: 0.1681 

Epoch: 4, Loss: 1.2483, w: 2.0734, b: 0.0269
lr * grad w: -0.3765, lr * grad b: -0.1579 

Epoch: 5, Loss: 0.6303, w: 2.4499, b: 0.1848
lr * grad w: 0.2672, lr * grad b: 0.0619 

Epoch: 6, Loss: 0.3488, w: 2.1827, b: 0.1229
lr * grad w: -0.1646, lr * grad b: -0.0841 

Epoch: 7, Loss: 0.2185, w: 2.3472, b: 0.2070
lr * grad w: 0.1243, lr * grad b: 0.0150 

Epoch: 8, Loss: 0.1563, w: 2.2229, b: 0.1920
lr * grad w: -0.0697, lr * grad b: -0.0502 

Epoch: 9, Loss: 0.1250, w: 2.2926, b: 0.2422
lr * grad w: 0.0599, lr * grad b: -0.0053 

Epoch: 10, Loss: 0.1077,

- What do these numbers represent?

- Why do they change each epoch?

---
**Note:** How gradients flow and influence to update the weights and biases 
---

---
If we understand this loop:

- CNNs are just bigger versions
- RNNs are just loops inside loops
- Transformers are parallel versions

**This loop is the engine of AI.**

# Interaction

### 1️⃣ Why `zero_grad()`


- `zero_grad()` does not free the graph.
  
- It clears the `.grad` buffers of parameters.


Graph is freed by backward() automatically.

Gradients live in parameter buffers.

So:
```python
loss.backward()   # builds grads
optimizer.zero_grad()   # clears old grads
```

***

### 2️⃣ Why gradients accumulate (the real reason)



Inside PyTorch:
```bash
param.grad = param.grad + new_gradient
```
NOT
```bash
param.grad = new_gradient
```
So if you skip `zero_grad()`:

| Epoch | Gradient stored |
| ----- | --------------- |
| 1     | g₁              |
| 2     | g₁ + g₂         |
| 3     | g₁ + g₂ + g₃    |
| …     | keeps growing   |


That’s gradient accumulation.

### 3️⃣ Why loss explodes when we skip `zero_grad()`


Let’s see what optimizer does:

$𝑤 = 𝑤 − \eta⋅grad$


If grad = g₁ + g₂ + g₃ + …

Then:

- Update becomes huge

- Model overshoots

- Loss increases instead of decreases

This is not “true exploding gradients”.
- It is wrong gradient accumulation.

### 4️⃣ Exploding gradients vs accumulated gradients


| Exploding gradients        | Accumulated gradients               |
| -------------------------- | ----------------------------------- |
| Comes from deep nets, RNNs | Comes from forgetting `zero_grad()` |
| Mathematical instability   | Programming mistake                 |
| Solved by clipping         | Solved by zeroing                   |


`zero_grad()` = accumulation bug, not mathematical explosion.

### 5️⃣ Why `.grad` changes every epoch


As `w` and `b` move closer to solution:

- Loss curve flattens

- Gradients shrink

- Model converges

This is optimization in action.